name: Web-App CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        working-directory: ../../Forc.WebApp
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}

      - name: run CI
        working-directory: ../../Forc.WebApp
        run: |
          npm install # or yarn install
          npm run lint # or yarn lint
          npm run build # or yarn build
